### ISSUE TITLE
initial feature roadmap

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaBrewing/BrewingRecipes.jl#1]
- [ ] Basic ingredient structs - these based on BeerJSON schemas?
    - [ ] `Fermentable`
    - [ ] `Hop`
    - [ ] `Yeast`
    - [ ] `Water`
- [ ] Basic processes
    - [ ] Mash
        - [ ] Tun loss
        - [ ] Grain absorption
        - [ ] GU yield
        - [ ] Water/heat additions
        - [ ] Decoction?
    - [ ] Boil
        - [ ] IBU calculations
        - [ ] Boiloff
    - [ ] Ferment
- [ ] BeerXML import
- [ ] BeerJSON import/export
